language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
env:
  global:
    - RELEASE_BRANCH=main
    - POST_RELEASE_BRANCH=main
    - RELEASE_MESSAGE=release
before_script:
  - npm install -g yaml-cli
  - npm install
  - npm run build
  - npm run postman
  - npm run version:prepare
  - npm run version:pack
script:
  - npm test
deploy:
  - provider: releases
    skip_cleanup: true
    file:
      - _build/openapi3.yml
      - _build/postman.json
    api_key: $GITHUB_TOKEN
jobs:
  include:
    - stage: test
      name: test
      script: npm test
    - stage: deploy
      name: githubPages
      script: /bin/sh travis/githubPages.sh
      if: branch = env(RELEASE_BRANCH)
    - stage: release
      name: release
      script: /bin/sh travis/release.sh
      if: branch = env(RELEASE_BRANCH) AND type = api AND commit_message = env(RELEASE_MESSAGE)
