language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - npm run build
  - npm test
  - npm run postman
  - npm run version:prepare
  - npm run version:pack
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/githubPages.sh
    on:
      branch: main
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
  - provider: releases
    skip_cleanup: true
    file:
      - _build/openapi3.yml
      - _build/postman.json
    api_key: $GITHUB_TOKEN
    on:
      tags: true
