# Core - Account
"/accounts":
  get:
    $ref: "./core/account/routes/searchAccounts.yml"
  post:
    $ref: "./core/account/routes/getAccountsInfo.yml"
"/accounts/{accountId}":
  get:
    $ref: "./core/account/routes/getAccountInfo.yml"

# Core - Block
"/blocks":
  get:
    $ref: "./core/block/routes/searchBlocks.yml"
"/blocks/{height}":
  get:
    $ref: "./core/block/routes/getBlockByHeight.yml"
"/blocks/{height}/transactions/{hash}/merkle":
  get:
    $ref: "./core/block/routes/getMerkleTransaction.yml"
"/blocks/{height}/statements/{hash}/merkle":
  get:
    $ref: "./core/block/routes/getMerkleReceipts.yml"

# Core - Chain
/chain/info:
  get:
    $ref: "./core/chain/routes/getChainInfo.yml"

# Core - Finalization
"/finalization/proof/epoch/{epoch}":
  get:
    $ref: "./core/finalization/routes/getFinalizationProofAtEpoch.yml"
"/finalization/proof/height/{height}":
  get:
    $ref: "./core/finalization/routes/getFinalizationProofAtHeight.yml"

# Core - Network
/network:
  get:
    $ref: "./core/network/routes/getNetworkType.yml"
/network/fees/rental:
  get:
    $ref: "./core/network/routes/getRentalFees.yml"
/network/fees/transaction:
  get:
    $ref: "./core/network/routes/getTransactionFees.yml"

/network/properties:
  get:
    $ref: "./core/network/routes/getNetworkProperties.yml"

# Core - Node
/node/health:
  get:
    $ref: "./core/node/routes/getNodeHealth.yml"
/node/info:
  get:
    $ref: "./core/node/routes/getNodeInfo.yml"
/node/peers:
  get:
    $ref: "./core/node/routes/getNodePeers.yml"
/node/storage:
  get:
    $ref: "./core/node/routes/getNodeStorage.yml"
/node/time:
  get:
    $ref: "./core/node/routes/getNodeTime.yml"
/node/server:
  get:
    $ref: "./core/node/routes/getServerInfo.yml"

# Core - Transaction
/transactions:

  put:
    $ref: "./core/transaction/routes/announceTransaction.yml"
"/transactions/confirmed":
  get:
    $ref: "./core/transaction/routes/searchConfirmedTransactions.yml"
  post:
    $ref: "./core/transaction/routes/getConfirmedTransactions.yml"
"/transactions/confirmed/{transactionId}":
  get:
    $ref: "./core/transaction/routes/getConfirmedTransaction.yml"
"/transactions/unconfirmed":
  get:
    $ref: "./core/transaction/routes/searchUnconfirmedTransactions.yml"
  post:
    $ref: "./core/transaction/routes/getUnconfirmedTransactions.yml"
"/transactions/unconfirmed/{transactionId}":
  get:
    $ref: "./core/transaction/routes/getUnconfirmedTransaction.yml"

# Core - Transaction Status
/transactionStatus:
  post:
    $ref: "./core/transaction/routes/getTransactionStatuses.yml"
"/transactionStatus/{hash}":
  get:
    $ref: "./core/transaction/routes/getTransactionStatus.yml"

# Plugin - Aggregate
/transactions/partial:
  get:
    $ref: "./core/transaction/routes/searchPartialTransactions.yml"
  put:
    $ref: "./plugins/aggregate/routes/announcePartialTransaction.yml"
  post:
    $ref: "./core/transaction/routes/getPartialTransactions.yml"
"/transactions/partial/{transactionId}":
  get:
    $ref: "./core/transaction/routes/getPartialTransaction.yml"
/transactions/cosignature:
  put:
    $ref: "./plugins/aggregate/routes/announceCosignatureTransaction.yml"

# Plugin - LockHash
"/account/{address}/lock/hash":
  get:
    $ref: "./plugins/lock_hash/routes/searchHashLock.yml"

"/lock/hash/{hash}":
  get:
    $ref: "./plugins/lock_hash/routes/getHashLock.yml"

# Plugin - LockSecret
"/account/{address}/lock/secret":
  get:
    $ref: "./plugins/lock_secret/routes/searchSecretLock.yml"

# Plugin - Metadata
"/metadata":
  get:
    $ref: "./plugins/metadata/routes/searchMetadataEntries.yml"

# Plugin - Mosaic
"/mosaics/{mosaicId}":
  get:
    $ref: "./plugins/mosaic/routes/getMosaic.yml"
/mosaics:
  get:
    $ref: "./plugins/mosaic/routes/searchMosaics.yml"
  post:
    $ref: "./plugins/mosaic/routes/getMosaics.yml"

# Plugin - Multisig
"/account/{address}/multisig":
  get:
    $ref: "./plugins/multisig/routes/getAccountMultisig.yml"
"/account/{address}/multisig/graph":
  get:
    $ref: "./plugins/multisig/routes/getAccountMultisigGraph.yml"

# Plugin - Namespace
"/namespaces":
  get:
    $ref: "./plugins/namespace/routes/searchNamespaces.yml"
"/namespaces/{namespaceId}":
  get:
    $ref: "./plugins/namespace/routes/getNamespace.yml"
/namespaces/names:
  post:
    $ref: "./plugins/namespace/routes/getNamespacesNames.yml"
/namespaces/account/names:
  post:
    $ref: "./plugins/namespace/routes/getAccountsNames.yml"
/namespaces/mosaic/names:
  post:
    $ref: "./plugins/namespace/routes/getMosaicsNames.yml"

# Plugin - Receipt
"/statements/transaction":
  get:
    $ref: "./plugins/receipt/routes/searchTransactionStatements.yml"
"/statements/resolutions/address":
  get:
    $ref: "./plugins/receipt/routes/searchAddressResolutionStatements.yml"
"/statements/resolutions/mosaic":
  get:
    $ref: "./plugins/receipt/routes/searchMosaicResolutionStatements.yml"

# Plugin - RestrictionAccount
"/restrictions/account/{address}":
  get:
    $ref: "./plugins/restriction_account/routes/getAccountRestrictions.yml"

# Plugin - RestrictionMosaic
"/restrictions/mosaic":
  get:
    $ref: "./plugins/restriction_mosaic/routes/searchMosaicRestrictions.yml"
